#!/usr/bin/env python3

def solution(S):
    for i in range(len(S)):
        if S[i] == "A" and S[i+1] == "B" or S[i + 1] == "A" and S[i] == "B":
            S.remove(A[i])
            S.remove(A[i+1])
        if S[i] == "C" and S[i+1] == "D" or S[i + 1] == "C" and S[i] == "D":
            S.remove(A[i])
            S.remove(A[i+1])
    return S

print(solution("ABCDA"))

